name: CI
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke import (libs + src)
        env:
          PYTHONPATH: .
        run: |
          python - <<'PY'
          import sys
          print("python:", sys.version.split()[0])
          import numpy, pandas, sklearn
          print("libs ok:", numpy.__version__, pandas.__version__)
          import src
          print("src ok:", getattr(src, "__file__", "pkg"))
          PY

  # optional: lint as non-blocking (won't fail the workflow)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install linters
        run: python -m pip install black flake8
      - name: Black (non-blocking)
        run: black --check .
        continue-on-error: true
      - name: Flake8 (non-blocking)
        run: flake8 .
        continue-on-error: true

